### ISSUE TITLE
Build Guide page is not found

### ISSUE THREAD

**Issue by ohchiko** [Spaceboards/SpaceboardsHardware#1]
## Issue is with:
Build Guide page

## The file that has issues:
- [x] Documentation
- [ ] KiCad File
- [ ] Gerber File
- [ ] Other

## Notes:
The link to the build guide page brings me a `404 (Not Found)` page. The link needs a fix.

**Comment by canuckkat** [comment]
2% Milk build guide is still giving a 404. https://spaceboards.xyz/hardware/2milkbuild

**Comment by LostQuasar** [comment]
> 
> 
> 2% Milk build guide is still giving a 404. https://spaceboards.xyz/hardware/2milkbuild

https://github.com/Spaceman/SpaceboardsWebsite/tree/1fa74fe9cdefebd895d806b8310ce51ae5415b56

**Comment by canuckkat** [comment]
AHHH. Thank you!
